Switched deps from an argument parser to shell parser, fixed bugs in build, test and make-jar scripts

diff --git a/util/make-jar b/util/make-jar
--- a/util/make-jar
+++ b/util/make-jar
@@ -2,18 +2,17 @@
 #Capture root app directory
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../" && pwd )"
 
+#clean
+source "$DIR/util/clean"
+#test
+source "$DIR/util/test"
+
 function error {
 	echo "Error making jar, will now halt"
 	exit 1
 }
 
-echo "Building source..."
-source "$DIR/util/build"
-
-echo "Testing source..."
-source "$DIR/util/test"
-
-echo "Creating /bin"
+echo "Creating bin/"
 #make output directory
 mkdir -p "$DIR/bin"
 
@@ -24,8 +23,34 @@ pushd "$DIR/src" > /dev/null
 echo "Main-Class: app.Cli" > manifest-default-class.MF
 
 #jar up project class files
-echo "Placing app.jar in /bin"
+echo "Placing app.jar in bin/"
 jar cfm "../bin/app.jar" manifest-default-class.MF app/*.class || error
+
+#make a temp folder to unzip into
+temp_dir=$(mktemp -dt)
+
+	pushd "$temp_dir" > /dev/null
+
+	#get a list of dependency jars, don't include junit
+	deps_list=$(echo "$DIR"/deps/{asg.cliche,neo4j}/*.jar)
+	for uz in $deps_list
+		#unzip those jars into our temp folder
+		do unzip -o $uz > /dev/null || error
+	done
+
+	#get rid of this META-INF file since we need to overwrite it with our own
+	rm -rf "$temp_dir"/META-INF || error 
+	
+	#Unzip our jar's contents as well
+	unzip -o "$DIR"/bin/app.jar || error 
+
+	#Zip everything, including our deps into "app-with-deps.jar"
+	zip -r "$DIR"/bin/app-with-deps.jar * > /dev/null || error
+
+	popd > /dev/null
+
+#clean up temp directory
+rm -rf "$temp_dir"
 
 #remove default manifest
 rm manifest-default-class.MF
@@ -33,4 +58,4 @@ rm manifest-default-class.MF
 #go-back to users directory
 popd > /dev/null
 
-echo "Successfully made app.jar!"
+echo "Successfully made app.jar, app-with-deps.jar!"
